---
title: "R Notebook"
author: "Monika Las"
output:
  html_document:
    df_print: paged
---

Analiza liczby ofert na jednego mieszkanca

```{r message=FALSE, warning=FALSE}
require(magrittr)
require(dplyr)
require(rvest)
require(stringi)
```
Dalej wczytujemy dane

```{r}
otodom <- read.csv(file = "../data/otodom_cleaned_ver2.csv", stringsAsFactors = FALSE)
otodom = tbl_df(otodom)

statystyki_miast <- 
    html_session("https://pl.wikipedia.org/wiki/Miasta_w_Polsce_(statystyki)") %>%
    html_node("table") %>% #wyciaga elementy table, tabelka ma taki tag
    html_table(trim = TRUE) %>% # konwersja do data frameu
    set_colnames(c("miasto", "powiat", "wojewodztwo", "pow", "ludnosc", "gestosc")) %>% #zamieniam nazwy kolumn
    mutate(pow = as.numeric(stri_replace_all_fixed(pow, ",", ".")), #zamieniam przecinki na .
           ludnosc = as.numeric(stri_replace_all_regex(ludnosc, "[:space:]", ""))) #zamieniam spacje na brak spacji
```

Zmienna statystyki miast ma `r nrow(statystyki_miast)` wierszy. Tabela poniżej
```{r message=FALSE, warning=FALSE, paged.print=TRUE}
statystyki_miast

```
Analiza ofert na mieszkańca
```{r}

oferty <- otodom %>% 
    group_by(adres_miasto, adres_wojewodztwo) %>% 
    summarise(liczba_ofert = n())

oferty %<>% left_join(statystyki_miast, by = c("adres_miasto" = "miasto",
                                               "adres_wojewodztwo" = "wojewodztwo"))


oferty %<>%
    mutate(ofert_na_mieszkanca = liczba_ofert/ludnosc) %>% 
    arrange(desc(ofert_na_mieszkanca))
```
Otrzymujemy
```{r}
oferty
```
I jeszcze wykres

```{r message=FALSE, warning=FALSE}
ggplot2::ggplot(oferty) + ggplot2::geom_point(ggplot2::aes(liczba_ofert, ludnosc))
